name: CI
on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: run flask
        run: |
          cd backend
          pip install -r requirements.txt
          nohup python app.py &
          sleep 5
        
      - name: Test Flask app
        run: |
            curl -sSf http://127.0.0.1:5000/cats > /dev/null
            
      - name: Stop Flask app
        run: |
            pkill -f 'python app.py'